# Generated by Django 4.1 on 2022-08-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=1024)),
                ("imdb_rating", models.FloatField(blank=True)),
                ("number", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=1024)),
                ("imdb_rating", models.FloatField(blank=True)),
                ("n_of_seasons", models.PositiveSmallIntegerField(blank=True)),
                ("n_of_episodes", models.PositiveIntegerField(blank=True)),
                ("has_ended", models.BooleanField(blank=True)),
                ("genre", models.ManyToManyField(to="st.genre")),
            ],
        ),
        migrations.CreateModel(
            name="User_show_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_rating", models.FloatField()),
                ("last_episode_seen", models.PositiveSmallIntegerField(blank=True)),
                ("last_season_seen", models.PositiveSmallIntegerField(blank=True)),
                ("seen_all_available", models.BooleanField(blank=True)),
                ("user_comment", models.CharField(blank=True, max_length=2048)),
                (
                    "favorite_episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="st.episode",
                    ),
                ),
                (
                    "show",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="st.show"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(blank=True, max_length=1024)),
                ("imdb_rating", models.FloatField(blank=True)),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="st.show"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="st.season"
            ),
        ),
    ]
